### ISSUE TITLE
Unhandled promise rejection in submit.js

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1130]
UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `success` of 'undefined' or 'null'.
    at saveTempFile.then.then.then (/Users/myers/git/synbiohub/lib/views/submit.js:437:17)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
error: (node:75744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

This happens when you try to merge into existing collection an object that would overwrite an existing item (overwrite_merge == 2).  Submit is blocked as it should be, so it does not cause a noticeable problem, but it should be removed.

**Comment by cjmyers** [comment]
Fixed by PR #1157
