### ISSUE TITLE
Exception trying to run visualization plugins

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1189]
Actually, there is an error in the logs for her plugins:
error: Plugin run failed!
error: TypeError: Cannot read property 'status' of undefined
   at module.exports (/home/deploy/synbiohub_dev/lib/views/stream.js:31:15)
   at Layer.handle [as handle_request] (/home/deploy/synbiohub_dev/node_modules
/express/lib/router/layer.js:95:5)
   at next (/home/deploy/synbiohub_dev/node_modules/express/lib/router/route.js
:137:13)
   at Route.dispatch (/home/deploy/synbiohub_dev/node_modules/express/lib/route
r/route.js:112:3)
   at Layer.handle [as handle_request] (/home/deploy/synbiohub_dev/node_modules
/express/lib/router/layer.js:95:5)
   at /home/deploy/synbiohub_dev/node_modules/express/lib/router/index.js:281:2
2
   at param (/home/deploy/synbiohub_dev/node_modules/express/lib/router/index.j
s:354:14)
   at param (/home/deploy/synbiohub_dev/node_modules/express/lib/router/index.j
s:365:14)
   at Function.process_params (/home/deploy/synbiohub_dev/node_modules/express/
lib/router/index.js:410:3)
   at next (/home/deploy/synbiohub_dev/node_modules/express/lib/router/index.js
:275:10)
   at initialize (/home/deploy/synbiohub_dev/node_modules/passport/lib/middlewa
re/initialize.js:53:5)
   at Layer.handle [as handle_request] (/home/deploy/synbiohub_dev/node_modules
/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/deploy/synbiohub_dev/node_modules/express/lib/router/i
ndex.js:317:13)
   at /home/deploy/synbiohub_dev/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/home/deploy/synbiohub_dev/node_modules/express/
lib/router/index.js:335:12)
   at next (/home/deploy/synbiohub_dev/node_modules/express/lib/router/index.js
:275:10)

**Comment by cjmyers** [comment]
Fixed
