### ISSUE TITLE
Delete user with invalid id causes promise exception

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1212]
curl -X POST -H "Accept: text/plain" -H "X-authorization: ef82f692-c35c-4761-8b74-049f2cc02e01" -d "id=2" http://localhost:7777/admin/deleteUser

Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/Users/myers/git/synbiohub/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/myers/git/synbiohub/node_modules/express/lib/response.js:170:12)
    at Model.db.model.User.findById.then.then.catch (/Users/myers/git/synbiohub/lib/actions/admin/deleteUser.js:14:28)

**Comment by cjmyers** [comment]
Same problem with updateUser
