### ISSUE TITLE
Can't submit genbank

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub#1346]
If you try and submit genbank to synbiohub it gives the error:

Error: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.sbolstandard.core2.GenBank.read(GenBank.java:1332)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:700)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:625)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:512)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:437)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:422)
	at org.sbolstandard.core2.SBOLValidate.validate(SBOLValidate.java:2726)
	at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:292)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cjmyers** [comment]
I see you closed this right away.  Is it resolved?
