### ISSUE TITLE
Unhandled promise rejection for invalid SPARQL query

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#1474]
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
error: Stream c39481a9-c806-48b8-9019-0897b733eb76 status is not found
error: (node:6) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/synbiohub/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/synbiohub/node_modules/express/lib/response.js:170:12)
    at search.then.catch (/synbiohub/lib/views/search.js:207:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
error: (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
error: Stream 94643a36-8b0f-4397-bdf6-3f4d251a5b56 status is not found
error: Stream 38788778-d463-4bbb-aeb2-1cd8671746b9 status is not found
error: Stream 3dd51496-f281-4ac2-877a-3eba4e1b7be0 status is not found
error: Stream ace9cb0d-b626-4e0f-87c5-2196fb9ee44a status is not found
error: Virtuoso not responding
error: Error: Virtuoso 37000 Error SP030: SPARQL compiler, line 0: Bad character '\' (0x5c) in SPARQL expression at '\'

**Comment by cjmyers** [comment]
Not sure how to reproduce
