### ISSUE TITLE
Remove submission is broken

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#209]
TypeError: Cannot read property '0' of undefined
    at module.exports (/Users/myers/git/synbiohub/lib/actions/removeSubmission.js:17:31)
    at Layer.handle [as handle_request] (/Users/myers/git/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/myers/git/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at requireUser (/Users/myers/git/synbiohub/lib/app.js:261:13)
    at Layer.handle [as handle_request] (/Users/myers/git/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/myers/git/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/myers/git/synbiohub/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/myers/git/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at /Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:281:22
    at param (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/myers/git/synbiohub/node_modules/express/lib/router/index.js:275:10)

**Comment by cjmyers** [comment]
fixed
