### ISSUE TITLE
MakePublic is broken

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#210]
Error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>406 Not Acceptable</title> </head><body> <h1>406 Not Acceptable</h1> <p>An appropriate representation of the requested resource sparql could not be found on this server.</p> Available variant(s): <ul> <li><a href="sparql">sparql</a> , type application/sparql-results+xml, charset UTF-8</li> </ul> </body></html> at Request.request [as _callback] (/Users/myers/git/synbiohub/lib/sparql/sparql.js:56:24) at Request.self.callback (/Users/myers/git/synbiohub/node_modules/request/request.js:188:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (/Users/myers/git/synbiohub/node_modules/request/request.js:1171:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) at IncomingMessage.<anonymous> (/Users/myers/git/synbiohub/node_modules/request/request.js:1091:12) at IncomingMessage.g (events.js:291:16) at emitNone (events.js:91:20) at IncomingMessage.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by cjmyers** [comment]
Fixed
