### ISSUE TITLE
Progress bars when submitting, making public, retrieving SBOL

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#216]

**Comment by cjmyers** [comment]
Turns out to be a bit too involved for 1.0.  Also, likely not an issue for typical uploads.

**Comment by 16zzundel5** [comment]
I'm closing this issue and moving it to the [roadmap](http://wiki.synbiohub.org/wiki/Roadmap).

**Comment by cjmyers** [comment]
This is not roadmap, this is a big usability, scalability priority.  When any task is large, we have the browser giving up on this, which is a big problem.

**Comment by 16zzundel5** [comment]
Okay, sorry, thought it was just a GUI thing.

**Comment by cjmyers** [comment]
Actual progress less important than just making sure browser does not die during long requests.

**Comment by cjmyers** [comment]
I added the line below to lib/api/sbol.js and it appears to have prevented the timeout of a large SBOL download.  Maybe this is the solution we have been looking for:

req.setTimeout(0) // no timeout

Where else should we use this?

submit.js
sparql.js
makePublic.js
copyFromRemote.js
remove.js
cloneSubmission.js

Anywhere else?  

If not, this should still be tested more and if okay, then moved to 1.1 as the progress bar would still be nice to include.

**Comment by 16zzundel5** [comment]
I pulled the latest version and get the following error on copying from remote:
Error
TypeError: Cannot read property 'childNodes' of undefined at RdfLibParser.parse (/home/zach/projects/synbiohub/node_modules/sboljs/node_modules/rdf-parser-rdfxml/index.js:226:28) at /home/zach/projects/synbiohub/node_modules/sboljs/node_modules/rdf-parser-rdfxml/index.js:624:31 at RdfXmlParser.process (/home/zach/projects/synbiohub/node_modules/sboljs/node_modules/rdf-parser-rdfxml/index.js:577:10) at /home/zach/projects/synbiohub/node_modules/sboljs/node_modules/rdf-parser-rdfxml/node_modules/rdf-parser-dom/node_modules/rdf-parser-abstract/index.js:19:10 at RdfXmlParser.AbstractParser.parse (/home/zach/projects/synbiohub/node_modules/sboljs/node_modules/rdf-parser-rdfxml/node_modules/rdf-parser-dom/node_modules/rdf-parser-abstract/index.js:18:10) at loadNextSource (/home/zach/projects/synbiohub/node_modules/sboljs/lib/load/rdf/loadRDF.js:68:16) at load (/home/zach/projects/synbiohub/node_modules/sboljs/lib/load/rdf/loadRDF.js:64:5) at SBOLDocument.loadRDF (/home/zach/projects/synbiohub/node_modules/sboljs/lib/SBOLDocument.js:614:9) at Function.loadRDF (/home/zach/projects/synbiohub/node_modules/sboljs/lib/SBOLDocument.js:579:22) at Request.request [as _callback] (/home/zach/projects/synbiohub/lib/ice.js:272:26) at Request.self.callback (/home/zach/projects/synbiohub/node_modules/request/request.js:188:22) at emitTwo (events.js:106:13) at Request.emit (events.js:192:7) at Request.<anonymous> (/home/zach/projects/synbiohub/node_modules/request/request.js:1171:10) at emitOne (events.js:96:13) at Request.emit (events.js:189:7)

**Comment by cjmyers** [comment]
Are you copying from ICE?  If so, which instance and which part? There are some issues with ice bugs at the moment.

Chris

**Comment by cjmyers** [comment]
One more thing to check is if you go to the ice instance and try to download SBOL 2 from there for the same part.

Chris

**Comment by cjmyers** [comment]
Seems to not be timing out anymore, but adding progress bars still useful.  Taking off 1.0.

**Comment by zachzundel** [comment]
- [ ] uploading
- [ ] making public
- [ ] retrieving SBOL
