### ISSUE TITLE
Cannot remove part from collection

### ISSUE THREAD

**Issue by dwootton** [SynBioHub/synbiohub#454]
When I try to remove a duplicate part from my collection, I get this error and the part is not removed: 
**url:** https://synbiohub.utah.edu/user/woottondylan/LACQ_SWITCH/attachment_00009O5TsBPkZrlGpoO8p6/1/remove
**Error:** 
TypeError: Cannot read property '0' of undefined
    at module.exports (/root/synbiohub/lib/actions/remove.js:19:31)
    at Layer.handle [as handle_request] (/root/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at requireUser (/root/synbiohub/lib/app.js:400:13)
    at Layer.handle [as handle_request] (/root/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/synbiohub/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at /root/synbiohub/node_modules/express/lib/router/index.js:281:22
    at param (/root/synbiohub/node_modules/express/lib/router/index.js:354:14)
    at param (/root/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at param (/root/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at param (/root/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at param (/root/synbiohub/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/root/synbiohub/node_modules/express/lib/router/index.js:410:3)
    at next (/root/synbiohub/node_modules/express/lib/router/index.js:275:10)

**Comment by schnauzer** [comment]
👍 I also have this problem.

**Comment by cjmyers** [comment]
I think I've fixed this one.  Could you let me know if this works now?  Thanks.

**Comment by dwootton** [comment]
After clicking remove part on one of the attachments in my switch, it routed me back to my submissions page. When I tried clicking on my switch again, it gave me the following error: 

Error: https://synbiohub.utah.edu/user/woottondylan/LACQ_SWITCH/attachment_00009O5TwfzqoboyqHPtgm/1 not found
    at sparql.queryJson.then (/root/synbiohub/lib/fetch/local/fetch-sbol-object-recursive.js:68:28)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by cjmyers** [comment]
The issue is the attachment has been removed, but the reference to the attachment remains.  When an attachment is removed, all references to the attachment should be removed as well.  

As a stop gap temporary solution, I’ve add the ability to display a message about the missing attachment, so the page should be able to be opened.  Please confirm that you can now open your page, but please leave the issue open as we should enable future attachment removals to also remove the references.

**Comment by dwootton** [comment]
I can open the page again.

**Comment by cjmyers** [comment]
I think I’ve fixed this so it will cleanly delete attachments now.  Any old deletes will still show up as missing attachments, but new ones will be cleanly removed.  Please test and let me know if it works for you now.

**Comment by dwootton** [comment]
It works with no errors.
