### ISSUE TITLE
Unable to download file with single GenericTopLevel

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#477]
This exception occurs when attempting to download SBOL for the collection created by the teat file: CreateAndRemoveGenericTopLevel.xml

Error: java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at org.sbolstandard.core2.SBOLReader.parseGenericTopLevel(SBOLReader.java:2977)
	at org.sbolstandard.core2.SBOLReader.readTopLevelDocs(SBOLReader.java:1022)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:659)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:561)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:448)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:379)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:364)
	at org.sbolstandard.core2.SBOLValidateSilent.validate(SBOLValidateSilent.java:1594)
	at org.synbiohub.RDFToSBOLJob.execute(RDFToSBOLJob.java:37)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

    at responseCallbacks.(anonymous function) (/Users/myers/git/synbiohub/lib/java.js:72:24)
    at DestroyableTransform.javaProcess.stdout.pipe.on (/Users/myers/git/synbiohub/lib/java.js:34:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at DestroyableTransform.Readable.push (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at DestroyableTransform.Transform.push (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at DestroyableTransform.write [as _transform] (/Users/myers/git/synbiohub/node_modules/binary-split/index.js:24:14)
    at DestroyableTransform.Transform._read (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by cjmyers** [comment]
Same with: 
multipleGenericTopLevel.xml

**Comment by cjmyers** [comment]
Fixed with libSBOLj issue #493
