### ISSUE TITLE
Exception when uploading files with non-compliant URIs

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#478]
This exception occurs for files with non_compliant URIs, such as those *_orig.xml test cases like:
pIKE_left_cassette_orig.xml

Error: java.lang.NullPointerException
	at org.sbolstandard.core2.SBOLDocument.extractDocumentURIPrefix(SBOLDocument.java:1435)
	at org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(SBOLDocument.java:1779)
	at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:119)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

    at responseCallbacks.(anonymous function) (/Users/myers/git/synbiohub/lib/java.js:72:24)
    at DestroyableTransform.javaProcess.stdout.pipe.on (/Users/myers/git/synbiohub/lib/java.js:34:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at DestroyableTransform.Readable.push (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at DestroyableTransform.Transform.push (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at DestroyableTransform.write [as _transform] (/Users/myers/git/synbiohub/node_modules/binary-split/index.js:24:14)
    at DestroyableTransform.Transform._read (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by cjmyers** [comment]
Another exception: partial_pTAK_left_cassette_orig.xml

Error: org.sbolstandard.core2.SBOLValidationException: sbol-10204: The displayId property of an Identified object is OPTIONAL and MAY contain a String that MUST be composed of only alphanumeric or underscore characters and MUST NOT begin with a digit.
Reference: SBOL Version 2.1.0 Section 7.4 on page 17
: https://synbiohub.org/user/myers/test/pTAKLeftCassete/null/1
	at org.sbolstandard.core2.Identified.setDisplayId(Identified.java:245)
	at org.sbolstandard.core2.ComponentDefinition.createSequenceConstraint(ComponentDefinition.java:1472)
	at org.sbolstandard.core2.ComponentDefinition.createSequenceConstraint(ComponentDefinition.java:1448)
	at org.sbolstandard.core2.ComponentDefinition.copy(ComponentDefinition.java:168)
	at org.sbolstandard.core2.SBOLDocument.createCopy(SBOLDocument.java:1305)
	at org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(SBOLDocument.java:1784)
	at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:119)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

    at responseCallbacks.(anonymous function) (/Users/myers/git/synbiohub/lib/java.js:72:24)
    at DestroyableTransform.javaProcess.stdout.pipe.on (/Users/myers/git/synbiohub/lib/java.js:34:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at DestroyableTransform.Readable.push (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at DestroyableTransform.Transform.push (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at DestroyableTransform.write [as _transform] (/Users/myers/git/synbiohub/node_modules/binary-split/index.js:24:14)
    at DestroyableTransform.Transform._read (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users/myers/git/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by cjmyers** [comment]
Fixed in libSBOLj
