### ISSUE TITLE
Error when uploading GenBank file

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#497]
While attempting to upload a GenBank file to a private collection, I run into the following error:

```
Error: split_to_n3 returned exit code 1
    at ChildProcess.splitProcess.on (/home/deploy/synbiohub/lib/sparql/sparql.js:360:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

**Comment by cjmyers** [comment]
This is actually a bug in the GenBank to SBOL conversion.  The conversion encountered an annotation tag that starts with a % and this when converted into an XML tag is not valid XML.  Will move this bug to the libSBOLj tracker.
