### ISSUE TITLE
Error in sending to Benchling - parts without sequence

### ISSUE THREAD

**Issue by AGMoreno** [SynBioHub/synbiohub#508]
If a part has no sequence, you'll get an error when clicking on the 'Send to Benchling' button.

**Comment by cjmyers** [comment]
This is indeed correct.  This is a Benchling error.  It will not allow the transfer of an empty sequence.  We should though improve the error message.

**Comment by AGMoreno** [comment]
I thought so. Yes, the error should be clear on this.

A!

2017-10-20 15:07 GMT+01:00 cjmyers <notifications@github.com>:

**Comment by cjmyers** [comment]
When copying to Benchling fails the error messages can be cryptic like 400. Need to actually catch and display the actual Benchling error message.

A common one is when some part has no sequence. This can create the exception below. Should either report a better error message or simply collapse away parts with no sequence.

TypeError: Cannot read property 'length' of undefined
at cd.sequenceAnnotations.forEach (/root/synbiohub/lib/actions/createBenchlingSequence.js:161:45)
at Array.forEach (native)
at flattenSequenceAnnotations (/root/synbiohub/lib/actions/createBenchlingSequence.js:159:29)
at fetchSBOLObjectRecursive.then (/root/synbiohub/lib/actions/createBenchlingSequence.js:98:2)
at process._tickCallback (internal/process/next_tick.js:103:7)

(taken from #523)

**Comment by cjmyers** [comment]
Now presents user with the error being returned from Benchling.
