### ISSUE TITLE
Need better error messages when copying to Benchling fails

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#523]
When copying to Benchling fails the error messages can be cryptic like 400.  Need to actually catch and display the actual Benchling error message.

A common one is when some part has no sequence.   This can create the exception below.  Should either report a better error message or simply collapse away parts with no sequence.

TypeError: Cannot read property 'length' of undefined
    at cd.sequenceAnnotations.forEach (/root/synbiohub/lib/actions/createBenchlingSequence.js:161:45)
    at Array.forEach (native)
    at flattenSequenceAnnotations (/root/synbiohub/lib/actions/createBenchlingSequence.js:159:29)
    at fetchSBOLObjectRecursive.then (/root/synbiohub/lib/actions/createBenchlingSequence.js:98:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by cjmyers** [comment]
Duplicate #508
