### ISSUE TITLE
Error when trying to make a component public

### ISSUE THREAD

**Issue by schnauzer** [SynBioHub/synbiohub#527]
When trying to make [this component](https://synbiohub.utah.edu/user/ethanransom/EColi_Infection/EColi_Infection/1) public, I encounter the following error:

```
Error: java.lang.IllegalArgumentException: Unable to set default URI prefix to non-compliant value `https://synbiohub./'
	at org.sbolstandard.core2.SBOLDocument.setDefaultURIprefix(SBOLDocument.java:2692)
	at org.sbolstandard.core2.SBOLDocument.fixDocumentURIPrefix(SBOLDocument.java:1458)
	at org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(SBOLDocument.java:1784)
	at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:119)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

    at responseCallbacks.(anonymous function) (/root/synbiohub/lib/java.js:72:24)
    at DestroyableTransform.javaProcess.stdout.pipe.on (/root/synbiohub/lib/java.js:34:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk (/root/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:212:18)
    at DestroyableTransform.Readable.push (/root/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:171:10)
    at DestroyableTransform.Transform.push (/root/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at DestroyableTransform.write [as _transform] (/root/synbiohub/node_modules/binary-split/index.js:24:14)
    at DestroyableTransform.Transform._read (/root/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/root/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/root/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/root/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at DestroyableTransform.Writable.write (/root/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by cjmyers** [comment]
could you send a share link?

**Comment by schnauzer** [comment]
Absolutely, so sorry:

[https://synbiohub.utah.edu/user/ethanransom/EColi_Infection/EColi_Infection/1/844fe4633e779e4787de16f7eea304c9472072e8/share](https://synbiohub.utah.edu/user/ethanransom/EColi_Infection/EColi_Infection/1/844fe4633e779e4787de16f7eea304c9472072e8/share)

**Comment by cjmyers** [comment]
I think this is fixed now.  Could you test?

**Comment by schnauzer** [comment]
Looks like it worked! 

https://synbiohub.utah.edu/public/EColi_Infection/EColi_Infection_collection/1

**Comment by cjmyers** [comment]
Hmm well not quite. It copied in the SynBioHub parts. I think I’ve fixed that now.

Chris
