### ISSUE TITLE
The dba user on virtuoso needs SPARQL-UPDATE rights

### ISSUE THREAD

**Issue by chrisAta** [SynBioHub/synbiohub#570]
I built SynBioHub from scratch following the new instructions (mvn package), and it built perfectly. However, after setup, when I try to submit a file, I get this error:

```
Error
    at Request.request [as _callback] (/home/chris/Desktop/Dev/synbiohub/lib/sparql/sparql.js:322:28)
    at Request.self.callback (/home/chris/Desktop/Dev/synbiohub/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/chris/Desktop/Dev/synbiohub/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/chris/Desktop/Dev/synbiohub/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I tested this with four different files, all of which I got from synbiohub.org. I don't know if I did something wrong at setup or if this is a bug, can someone else test this?

**Comment by cjmyers** [comment]
This is a spraql error.  Seems an issue with virtuoso setup. Does dba user have sparql update rights?

Chris

**Comment by cjmyers** [comment]
Need to add to the README documentation that indicates that SPARQL_UPDATE rights need to be given to the dba user.

**Comment by oflatt** [comment]
README now reflects this.
