### ISSUE TITLE
Create a collection is broken

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#581]
Error
Error: getType: https://synbiohub.org/user/jakebeal/FACETS/Sorting/FACETS/Sorting_collection//removeCollection not found
    at sparql.queryJson.then (/home/deploy/synbiohub/lib/query/local/type.js:17:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by jakebeal** [comment]
This happened while trying to build a subcollection of a private project

**Comment by cjmyers** [comment]
Yep, slash in the id is the issue.
