### ISSUE TITLE
Problems with downloaded combine archive

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#609]
When I attempt to import the downloaded COMBINE archive into iBioSim, I get this error for all SBML/SED-ML files.

com.ctc.wstx.exc.WstxIOException: Invalid UTF-8 start byte 0x8b (at char #2, byte #-1)
	at com.ctc.wstx.sr.StreamScanner.constructFromIOE(StreamScanner.java:637)
	at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:1012)
	at com.ctc.wstx.sr.StreamScanner.getNext(StreamScanner.java:765)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2074)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1173)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:255)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromXMLEventReader(SBMLReader.java:611)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromStream(SBMLReader.java:576)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBML(SBMLReader.java:299)
	at org.sbml.jsbml.SBMLReader.readSBML(SBMLReader.java:116)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:105)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:92)
	at edu.utah.ece.async.ibiosim.dataModels.biomodel.util.SBMLutilities.readSBML(SBMLutilities.java:5758)
	at edu.utah.ece.async.ibiosim.gui.Gui.importCombineArchive(Gui.java:4264)
	at edu.utah.ece.async.ibiosim.gui.Gui.importArchive(Gui.java:4429)
	at edu.utah.ece.async.ibiosim.gui.Gui.actionPerformed(Gui.java:2388)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjmyers** [comment]
Looking inside all the XML files are binary files.

**Comment by zachzundel** [comment]
Hmm, how do you mean? They’re incorrectly classified on the manifest?

Thanks,
Zach

**Comment by zachzundel** [comment]
Okay, should be a quick fix. I’ll do it when I get back home and shoot you an email when I think I’ve fixed it. 

Thanks,
Zach

**Comment by cjmyers** [comment]
Actually, shouldn't we be dereferencing the source field?  The current approach is assuming they are locally stored, but they could be remote, either another synbiohub OR some other file resource?

**Comment by cjmyers** [comment]
This appears to be working now, but I will open a new issue to support more general fetching using attachment source field.
