### ISSUE TITLE
Too many open files problem

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#639]
We appear to have a files files problem.  We need to make sure all files that are opened get closed.

Error: EMFILE: too many open files, open 'templates/views/index.jade'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at handleTemplateCache (/home/tomcat/synbiohub/node_modules/pug/lib/index.js:136:37)
    at Object.exports.renderFile (/home/tomcat/synbiohub/node_modules/pug/lib/index.js:331:10)
    at module.exports (/home/tomcat/synbiohub/lib/views/index.js:14:18)
    at Layer.handle [as handle_request] (/home/tomcat/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tomcat/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/tomcat/synbiohub/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tomcat/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at /home/tomcat/synbiohub/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/tomcat/synbiohub/node_modules/express/lib/router/index.js:335:12)
    at next (/home/tomcat/synbiohub/node_modules/express/lib/router/index.js:275:10)
    at /home/tomcat/synbiohub/lib/app.js:198:13
    at Layer.handle [as handle_request] (/home/tomcat/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/tomcat/synbiohub/node_modules/express/lib/router/index.js:317:13)

**Comment by cjmyers** [comment]
The stack trace is the one given.  The problem is this is a file open leak, so the cause is just files not getting closed.  This is likely going to require a search for all locations in the code that open a file and double check that the file gets closed.  Not an easy one to sort I'm afraid.

**Comment by cjmyers** [comment]
This is appearing more often now.  I think this is a serious bug, so it should be fixed before 1.4.

**Comment by zachzundel** [comment]
Where is it currently happening? I’d like to take a look.

**Comment by cjmyers** [comment]
I’ve run into this after doing several submits in a row.

**Comment by cjmyers** [comment]
Actually it does not seem to appear as often as I thought.  Still should be checked out but removing priority.
