### ISSUE TITLE
Exception removing SBOL object from SBH

### ISSUE THREAD

**Issue by bbartley** [SynBioHub/synbiohub#671]
Not sure if I'm overlooking something obvious here, but the line below results in the following error trace:
`repository.removeSBOL(new URI("https://hub.sd2e.org/user/sd2e/scratch_test/scratch_test_collection/1"));
`
The URI is spoofed, so the repository instance actually refers to "https://hub-staging.sd2e.org".  Is this somehow causing the issue?  I also thought maybe it might be related to user account permissions.

org.synbiohub.frontend.SynBioHubException: Error reading SBOL
	at org.synbiohub.frontend.SynBioHubFrontend.fetchFromSynBioHub(SynBioHubFrontend.java:993)
	at org.synbiohub.frontend.SynBioHubFrontend.removeSBOL(SynBioHubFrontend.java:193)
	at com.bbn.sd2.SynBioHubAccessor.clean(SynBioHubAccessor.java:214)
	at com.bbn.sd2.TestSynBioHubAccessor.tearDownAfterClass(TestSynBioHubAccessor.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.sbolstandard.core2.SBOLValidationException: org.sbolstandard.core2.SBOLValidationException: sbol-10201: The identity property of an Identified object is REQUIRED and MUST contain a URI that adheres to the syntax defined by: “http://www.w3.org/1999/02/22-rdf-syntax#about”
Reference: SBOL Version 2.2.0 Section 7.4 on page 17
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:654)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:552)
	at org.synbiohub.frontend.SynBioHubFrontend.fetchFromSynBioHub(SynBioHubFrontend.java:989)
	... 18 more
Caused by: org.sbolstandard.core2.SBOLValidationException: sbol-10201: The identity property of an Identified object is REQUIRED and MUST contain a URI that adheres to the syntax defined by: “http://www.w3.org/1999/02/22-rdf-syntax#about”
Reference: SBOL Version 2.2.0 Section 7.4 on page 17
	at org.sbolstandard.core2.SBOLReader.readRDF(SBOLReader.java:772)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:641)
	... 20 more
Caused by: java.lang.ClassCastException: uk.ac.ncl.intbio.core.datatree.NamedProperty$Impl cannot be cast to uk.ac.ncl.intbio.core.datatree.IdentifiableDocument
	at uk.ac.ncl.intbio.core.io.rdf.RdfIo$2.updateDocumentInStackWithProperty(RdfIo.java:416)
	at uk.ac.ncl.intbio.core.io.rdf.RdfIo$2.updateDocumentInStack(RdfIo.java:377)
	at uk.ac.ncl.intbio.core.io.rdf.RdfIo$2.readTopLevelDocuments(RdfIo.java:297)
	at uk.ac.ncl.intbio.core.io.rdf.RdfIo$2.read(RdfIo.java:203)
	at org.sbolstandard.core2.SBOLReader.readRDF(SBOLReader.java:759)
	... 21 more

**Comment by cjmyers** [comment]
Please make sure you are using version 2.3.2-SNAPSHOT of libSBOLj.  Also, are you logged in when you call removeSBOL?

**Comment by cjmyers** [comment]
@bbartley can you comment on whether you sorted this issue?

**Comment by bbartley** [comment]
After upgrading to 2.3.2, it still throws an exception.  If I try deleting the non-spoofed URI, rather than the spoofed URI mentioned above: 

 https://hub-staging.sd2e.org/user/sd2e/scratch_test/scratch_test_collection/1

I get an exception that says the URI does not start with the same namespace as the repository (which seems like appropriate behavior).

It's not a major blocker, but it does mean I can't clean up objects created by automated tests.

**Comment by cjmyers** [comment]
When you declared the SBH frontend, you need to indicate both the URL and URI prefix like this:

SynBioHubFrontend sbh = new SynBioHubFrontend("https://hub-staging.sd2e.org","https://hub.sd2e.org”);

This should allow you to access/remove non-spoofed URIs.

**Comment by bbartley** [comment]
The issue is perhaps not related to spoofing at all.  I also tested on production instance of SD2 SBH with non-spoofed URIs.
```
repository.removeSBOL(new URI("https://hub.sd2e.org/user/sd2e/scratch_test/scratch_test_collection/1"));
```
The call does appear to delete the target object, but still results in an error trace.
```
org.synbiohub.frontend.SynBioHubException: Error reading SBOL
	at org.synbiohub.frontend.SynBioHubFrontend.fetchFromSynBioHub(SynBioHubFrontend.java:1044)
	at org.synbiohub.frontend.SynBioHubFrontend.removeSBOL(SynBioHubFrontend.java:211)
	at com.bbn.sd2.SynBioHubAccessor.clean(SynBioHubAccessor.java:213)
	at com.bbn.sd2.TestSynBioHubAccessor.tearDownAfterClass(TestSynBioHubAccessor.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.sbolstandard.core2.SBOLValidationException: org.sbolstandard.core2.SBOLValidationException: sbol-10201: Strong Validation Error:
The identity property of an Identified object is REQUIRED and MUST contain a URI that adheres to the syntax defined by: “http://www.w3.org/1999/02/22-rdf-syntax#about”
Reference: SBOL Version 2.2.1 Section 7.4 on page 17
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:723)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:604)
	at org.synbiohub.frontend.SynBioHubFrontend.fetchFromSynBioHub(SynBioHubFrontend.java:1040)
	... 18 more
Caused by: org.sbolstandard.core2.SBOLValidationException: sbol-10201: Strong Validation Error:
The identity property of an Identified object is REQUIRED and MUST contain a URI that adheres to the syntax defined by: “http://www.w3.org/1999/02/22-rdf-syntax#about”
Reference: SBOL Version 2.2.1 Section 7.4 on page 17
	at org.sbolstandard.core2.SBOLReader.readRDF(SBOLReader.java:828)
	at org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:697)
	... 20 more
Caused by: java.lang.ClassCastException: org.sbolstandard.core.datatree.NamedProperty$Impl cannot be cast to org.sbolstandard.core.datatree.IdentifiableDocument
	at org.sbolstandard.core.io.rdf.RdfIo$2.updateDocumentInStackWithProperty(RdfIo.java:417)
	at org.sbolstandard.core.io.rdf.RdfIo$2.updateDocumentInStack(RdfIo.java:378)
	at org.sbolstandard.core.io.rdf.RdfIo$2.readTopLevelDocuments(RdfIo.java:298)
	at org.sbolstandard.core.io.rdf.RdfIo$2.read(RdfIo.java:204)
	at org.sbolstandard.core2.SBOLReader.readRDF(SBOLReader.java:815)
	... 21 more

```

**Comment by cjmyers** [comment]
Ok, this was a pretty silly one.  I never meant the removeSBOL to be used by others.  I created for SynBioHub.  Anyway, what I did is reused the fetch code for the remove endpoint, so after the remove it tries to load the stream that is returned.  However, what is returned is not valid SBOL, of course.  I've deployed an updated snapshot of libSBOLj, which should have this sorted.  Please give it a try and let me know if the exception has gone away.

**Comment by bbartley** [comment]
Working now.
