### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by joseutrilla** [SynBioHub/synbiohub#699]
Not able to search or browse collections

TypeError: Cannot read property 'map' of undefined
    at sparql.queryJson.then (/home/deploy/synbiohub/lib/query/local/collection.js:61:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by cjmyers** [comment]
synbiohub.org was down during this time period.  It is back up now.  Can you check whether it is working for you now?  Thanks.

**Comment by cjmyers** [comment]
Fixed
