### ISSUE TITLE
public synbiohub 

### ISSUE THREAD

**Issue by jurquiza** [SynBioHub/synbiohub#720]
When submitting a SBOL file that does not contain sequence information the public service returns an error. 

Error

Error: java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:364)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at de.unirostock.sems.cbarchive.CombineArchive.init(CombineArchive.java:210)
	at de.unirostock.sems.cbarchive.CombineArchive.<init>(CombineArchive.java:138)
	at org.synbiohub.PrepareSubmissionJob.readCOMBINEArchive(PrepareSubmissionJob.java:102)
	at org.synbiohub.PrepareSubmissionJob.getFilenames(PrepareSubmissionJob.java:211)
	at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:240)
	at org.synbiohub.Main$1.run(Main.java:30)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

    at responseCallbacks.(anonymous function) (/opt/synbiohub/lib/java.js:89:24)
    at DestroyableTransform.javaProcess.stdout.pipe.on (/opt/synbiohub/lib/java.js:51:5)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at readableAddChunk (/opt/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:211:18)
    at DestroyableTransform.Readable.push (/opt/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:170:10)
    at DestroyableTransform.Transform.push (/opt/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at DestroyableTransform.write [as _transform] (/opt/synbiohub/node_modules/binary-split/index.js:24:14)
    at DestroyableTransform.Transform._read (/opt/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/opt/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/opt/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:337:64)
    at writeOrBuffer (/opt/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:326:5)
    at DestroyableTransform.Writable.write (/opt/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:263:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

**Comment by cjmyers** [comment]
Sorry for the trouble.  We migrated to a new server last week, and the Java version was not correct.  This should now be working now.  Could you please test and let us know?  Thanks.

**Comment by jurquiza** [comment]
So i tried again and how i get a different error 

Error: connect ECONNREFUSED 127.0.0.1:8891 at Object._errnoException (util.js:1022:11) at _exceptionWithHostPort (util.js:1044:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by cjmyers** [comment]
Fixed
