### ISSUE TITLE
Download log on admin page not working

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#747]
Error: ENOENT: no such file or directory, stat 'synbiohub.log'
    at Object.statSync (fs.js:871:3)
    at getLog (/synbiohub/lib/views/admin/log.js:14:19)
    at module.exports (/synbiohub/lib/views/admin/log.js:6:16)
    at Layer.handle [as handle_request] (/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at requireAdmin (/synbiohub/lib/app.js:495:13)
    at Layer.handle [as handle_request] (/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at next (/synbiohub/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/synbiohub/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/synbiohub/node_modules/express/lib/router/layer.js:95:5)
    at /synbiohub/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/synbiohub/node_modules/express/lib/router/index.js:335:12)
    at next (/synbiohub/node_modules/express/lib/router/index.js:275:10)
    at Model.db.model.User.findById.then (/synbiohub/lib/app.js:182:17)
    at Model.tryCatcher (/synbiohub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/synbiohub/node_modules/bluebird/js/release/promise.js:512:31)

**Comment by cjmyers** [comment]
Duplicate
