### ISSUE TITLE
Missing catch statements in submit.js

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#821]
There are missing catch statements in submit.js that are causing exceptions, such as:

unlinking:/tmp/OIu5bxwbVGiXqo3070l7zSM4
unlinking:/tmp/sbh_convert_validate4665895954903567965.xml
(node:14902) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/deploy/synbiohub_dev/node_modules/express/lib/response.js:767:10)
    at ServerResponse.contentType (/home/deploy/synbiohub_dev/node_modules/express/lib/response.js:595:15)
    at getCollectionMetaData.then.catch (/home/deploy/synbiohub_dev/lib/views/submit.js:403:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:14902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
(node:14902) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink '/tmp/OIu5bxwbVGiXqo3070l7zSM4'
(node:14902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)

**Comment by cjmyers** [comment]
Fixed in refactor
