### ISSUE TITLE
Unhandled promise rejection in sbol.js

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#968]
UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HE
ADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/synbiohub/node_modules/express/lib/response.js:77
1:10)
    at ServerResponse.send (/synbiohub/node_modules/express/lib/response.js:170:
12)
    at fetchSBOLSource.then.catch (/synbiohub/lib/api/sbol.js:38:11)
.[31merror.[39m:   (node:8) UnhandledPromiseRejectionWarning: Unhandled promise 
rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .cat
ch(). (rejection id: 1436)

**Comment by cjmyers** [comment]
Fixed by PR #1118
