### ISSUE TITLE
Unhandled promise rejection in collection.js

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#969]
UnhandledPromiseRejectionWarning: TypeError: Cannot 
read property 'map' of undefined
    at sparql.queryJson.then (/synbiohub/lib/query/local/collection.js:52:21)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
.[31merror.[39m:   (node:8) UnhandledPromiseRejectionWarning: Unhandled promise 
rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .cat
ch(). (rejection id: 2851)

**Comment by cjmyers** [comment]
This happens if Virtuoso has crashed.

**Comment by cjmyers** [comment]
Fixed by PR #1118
