### ISSUE TITLE
Unhandled promise rejection in sbolnr.js

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#971]
UnhandledPromiseRejectionWarning: Error [ERR_HTTP_H
EADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/synbiohub/node_modules/express/lib/response.js:77
1:10)
    at ServerResponse.send (/synbiohub/node_modules/express/lib/response.js:170:
12)
    at fetchSBOLSourceNonRecursive.then.catch (/synbiohub/lib/api/sbolnr.js:30:3
0)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
.[31merror.[39m:   (node:10) UnhandledPromiseRejectionWarning: Unhandled promise
 rejection. This error originated either by throwing inside of an async function
 without a catch block, or by rejecting a promise which was not handled with .ca
tch(). (rejection id: 2642)
.[31merror.[39m:   (node:10) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_H
EADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/synbiohub/node_modules/express/lib/response.js:77
1:10)
    at ServerResponse.send (/synbiohub/node_modules/express/lib/response.js:170:
12)
    at fetchSBOLSourceNonRecursive.then.catch (/synbiohub/lib/api/sbolnr.js:30:3
0)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
.[31merror.[39m:   (node:10) UnhandledPromiseRejectionWarning: Unhandled promise
 rejection. This error originated either by throwing inside of an async function
 without a catch block, or by rejecting a promise which was not handled with .ca
tch(). (rejection id: 2643)

**Comment by cjmyers** [comment]
Fixed by PR #1118
